### ISSUE TITLE
Android : libApplicationMain.so  missing lib

### ISSUE THREAD

**Issue by jgranick** [openfl/openfl-native#1]
#1 Issue by __kiroukou__,

Hello,

when I'm trying to compile any code using openfl to android, I get the following error :

```
E/ExternalAccountType(14174): Unsupported attribute readOnly
E/AndroidRuntime(14799): FATAL EXCEPTION: main
E/AndroidRuntime(14799): java.lang.UnsatisfiedLinkError: Couldn't load ApplicationMain: findLibrary returned null
E/AndroidRuntime(14799): at java.lang.Runtime.loadLibrary(Runtime.java:365)
E/AndroidRuntime(14799): at java.lang.System.loadLibrary(System.java:535)
E/AndroidRuntime(14799): at org.haxe.HXCPP.run(HXCPP.java:9)
E/AndroidRuntime(14799): at org.haxe.nme.GameActivity.onCreate(GameActivity.java:95)
E/AndroidRuntime(14799): at android.app.Activity.performCreate(Activity.java:4538)
E/AndroidRuntime(14799): at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1071)
E/AndroidRuntime(14799): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2161)
E/AndroidRuntime(14799): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2240)
E/AndroidRuntime(14799): at android.app.ActivityThread.access$600(ActivityThread.java:139)
E/AndroidRuntime(14799): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262)
E/AndroidRuntime(14799): at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(14799): at android.os.Looper.loop(Looper.java:156)
E/AndroidRuntime(14799): at android.app.ActivityThread.main(ActivityThread.java:4987)
E/AndroidRuntime(14799): at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(14799): at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(14799): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
E/AndroidRuntime(14799): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
E/AndroidRuntime(14799): at dalvik.system.NativeStart.main(Native Method)
E/EmbeddedLogger( 193): App crashed! Process: fr.motiontwin.openflBase
E/EmbeddedLogger( 193): App crashed! Package: fr.motiontwin.openflBase v1 (1.0.0)
E/EmbeddedLogger( 193): App crashed! Application Label: OpenFL Base App
```

After digging a bit, it seems that the libApplicationMain.so file is not generated !

I think the android build process has changed a lot compared to NME, so not sure it I catch the problem correctly, but any information/fix would help me a lot.

Thomas

**Comment by jgranick** [comment]
Comment by __kiroukou__:

seems that the build process does not call the Export/android/haxe/debug.hxml !
Also, if I call it manually to generate the libApplicationMain.so file, it is not linked anywhere. 

If i force it into the libs folder, it is removed during the build process...

No idea where to go from now

**Comment by jgranick** [comment]
Comment by __jgranick__:

I have posted a new openfl-native and openfl-tools to haxelib, with the same version. If you remove these libraries and reinstall, I believe Android should be working :)

**Comment by jgranick** [comment]
Comment by __kiroukou__:

Hi Joshua.

It is actually better indeed, but still not perfect ;-)

Here is the error I have now : 

```
--------- beginning of /dev/log/main
E/wpa_supplicant( 2879): Unsupported command: BTCOEXMODE 1
E/wpa_supplicant( 2879): Unsupported command: BTCOEXMODE 2
E/wpa_supplicant( 2879): Unsupported command: GATEWAY-ADD 4261521600
E/ExternalAccountType(14174): Unsupported attribute readOnly
E/ExternalAccountType(14174): Unsupported attribute readOnly
E/Exception(19304): Could not load module libnull@nme_byte_array_init__4
E/CFFILoader.h(19304): Could not API gc_set_top_of_stack
E/CFFILoader(19304): Could not resolve :gc_set_top_of_stack
F/libc    (19304): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1)
E/MediaScannerJNI(19327): An error occurred while scanning file '/mnt/sdcard/Notifications/hangout_ringtone.m4a'.
E/MediaProvider(19327): denny. getCompressedAlbumArt IOException
E/MediaProvider(19327): java.io.FileNotFoundException: Permission denied
E/MediaProvider(19327):         at android.os.Parcel.openFileDescriptor(Native Method)
E/MediaProvider(19327):         at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:116)
E/MediaProvider(19327):         at com.android.providers.media.MediaProvider.getCompressedAlbumArt(MediaProvider.java:6228)
E/MediaProvider(19327):         at com.android.providers.media.MediaProvider.makeThumbInternal(MediaProvider.java:6527)
E/MediaProvider(19327):         at com.android.providers.media.MediaProvider.getThumb(MediaProvider.java:6497)
E/MediaProvider(19327):         at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:4520)
E/MediaProvider(19327):         at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:5000)
E/MediaProvider(19327):         at com.android.providers.media.MediaProvider.insert(MediaProvider.java:4238)
E/MediaProvider(19327):         at android.content.ContentProvider$Transport.insert(ContentProvider.java:200)
E/MediaProvider(19327):         at android.media.MediaScanner$MyMediaScannerClient.endFile(MediaScanner.java:991)
E/MediaProvider(19327):         at android.media.MediaScanner$MyMediaScannerClient.doScanFile(MediaScanner.java:619)
E/MediaProvider(19327):         at android.media.MediaScanner.scanSingleFile(MediaScanner.java:1530)
E/MediaProvider(19327):         at com.android.providers.media.MediaScannerService.scanFile(MediaScannerService.java:708)
E/MediaProvider(19327):         at com.android.providers.media.MediaScannerService.access$100(MediaScannerService.java:82)
E/MediaProvider(19327):         at com.android.providers.media.MediaScannerService$ServiceHandler.handleMessage(MediaScannerService.java:952)
E/MediaProvider(19327):         at android.os.Handler.dispatchMessage(Handler.java:99)
E/MediaProvider(19327):         at android.os.Looper.loop(Looper.java:156)
E/MediaProvider(19327):         at com.android.providers.media.MediaScannerService.run(MediaScannerService.java:662)
E/MediaProvider(19327):         at java.lang.Thread.run(Thread.java:864)
E/MediaProvider(19327): denny. getCompressedAlbumArt IOException
E/MediaProvider(19327): java.io.FileNotFoundException: Permission denied
E/MediaProvider(19327):         at android.os.Parcel.openFileDescriptor(Native Method)
E/MediaProvider(19327):         at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:116)
E/MediaProvider(19327):         at com.android.providers.media.MediaProvider.getCompressedAlbumArt(MediaProvider.java:6228)
E/MediaProvider(19327):         at com.android.providers.media.MediaProvider.makeThumbInternal(MediaProvider.java:6527)
E/MediaProvider(19327):         at com.android.providers.media.MediaProvider.access$1600(MediaProvider.java:129)
E/MediaProvider(19327):         at com.android.providers.media.MediaProvider$4.handleMessage(MediaProvider.java:960)
E/MediaProvider(19327):         at android.os.Handler.dispatchMessage(Handler.java:99)
E/MediaProvider(19327):         at android.os.Looper.loop(Looper.java:156)
E/MediaProvider(19327):         at android.os.HandlerThread.run(HandlerThread.java:60)
E/AccessControl(19344): SIM: UICC rules not correctly initialized!!
E/Exception(19358): Could not load module libnull@nme_byte_array_init__4
E/CFFILoader.h(19358): Could not API gc_set_top_of_stack
E/CFFILoader(19358): Could not resolve :gc_set_top_of_stack
F/libc    (19358): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1)
F/libc    (19358): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1)
E/ExternalAccountType(14174): Unsupported attribute readOnly
E/ExternalAccountType(14174): Unsupported attribute readOnly
E/Exception(19559): Could not load module libnull@nme_byte_array_init__4
E/CFFILoader.h(19559): Could not API gc_set_top_of_stack
E/CFFILoader(19559): Could not resolve :gc_set_top_of_stack
F/libc    (19559): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1)
F/libc    (19559): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1)
```

Interessting part is "E/Exception(19559): Could not load module libnull@nme_byte_array_init__4"  I think.

From what I can see, everything seems fine on my filsystem (applicationMain.so is correctly generated).

Thomas

(fyi : I have correctly cleaned the project before )

**Comment by jgranick** [comment]
Comment by __jgranick__:

We're probably close, unfortunately I can't test without an Android device on hand, so I'll have to look later at why this is happening. It sounds like the problem is "flash.Lib.load" but curiously it works here for other targets

**Comment by jgranick** [comment]
Comment by __jgranick__:

Can you try the latest version and see if it works for you?

**Comment by jgranick** [comment]
Comment by __kiroukou__:

Hello Joshua,

I'll certainly do a test tomorrow at work and check if everything is
working as expected now.

I keep you in touch.
Thomas

kiroukou

2013/5/30 Joshua Granick notifications@github.com

**Comment by jgranick** [comment]
Comment by __jgranick__:

Everything looks good here. Let me know if you have more problems!
